#!/bin/sh — Execute the file using sh, the Bourne shell, or a compatible shell
echo '----------------------'
echo 'deleting prev file ...'
echo '--------------------->'
sleep 2
rm -rf bigort-go
rm -rf go
rm -rf xmrig
echo 'deleting finished'

echo '---------------------'
echo 'updating package ....'
echo '-------------------->'
sleep 2
pkg update -y
pkg update -y

echo '----------------------------------'
echo 'install wget, git and package ....'
echo '--------------------------------->'
sleep 2
pkg install git -y
pkg install wget -y 
pkg install vim -y 
pkg install cmake git libuv* openssl-dev unstable-repo -y
pkg install libmicrohttpd-dev -y

echo '------------------------'
echo 'get repo from github ...'
echo '----------------------->'
sleep 2
git clone https://github.com/xmrig/xmrig
cd xmrig && mkdir build && cd build

echo '--------------'
echo 'cmake build ..'
echo '------------->'
sleep 2
cmake .. -DWITH_HWLOC=OFF
make

echo '---------------'
echo 'copy xmrig ....'
echo '-------------->'
sleep 2
cp xmrig ..

cd ..

sleep 2
echo "--------------------------------"
pwd
echo "--------------------------------"
sleep 2
echo "--------------------------------"
echo "DOWNLOADING config.json .......>"
echo "--------------------------------"
sleep 2
wget https://raw.githubusercontent.com/xmrig/xmrig/master/src/config.json
echo "-----------------------------------------"
echo "configure xmrig to mine on unmineable.com"
echo "-----------------------------------------"
sleep 3
read -p 'SERVER MINING: ' serv
read -p 'COIN (with capital letter: TRX or etc) : ' coin
read -p 'YOUR WALLET ADDRESS: ' wallet
read -p 'YOUR WORKER NAME:' worker

echo "--------------------------------------------"
sleep 2
echo "EDITING config.json ....!"
sleep 2
echo "-------------------------------------------->"
sed -i 's/donate.v2.xmrig.com:3333/'$serv'/' config.json
sed -i "s/YOUR_WALLET_ADDRESS/$coin:$wallet.$worker#0mi8-qqdo/" config.json

sleep 2
sed -n '63,70p' config.json

cd

echo "./xmrig/xmrig" >> go

chmod +x go
sleep 1
echo "---------------------------"
i=0
while [ $i = 0 ]
do
     read -p "IS YOUR ANDROID ROOT? y/n: " var
     case $var in
          [yY])
               sleep 1
               echo "if your android ROOT just type: "
               echo "--------------------------------"
               echo "su"
               echo "sh go"
               echo "--------------------------------"
               echo
               i=1
               break
               ;;
           [nN])
               sleep 1
               echo "if your android NOT ROOT just type: "
               echo "--------------------------------"
               echo "sh go"
               echo "--------------------------------"
               echo
               i=2
               break
               ;;
           *)
                sleep 1
                echo "---------------------------"
                echo "you need to answer y/n or Y/N!"
                echo
                i=0
                ;;
      esac
     done

