#!/bin/sh — Execute the file using sh, the Bourne shell, or a compatible shell
echo 'updating package ....'
pkg update -y
pkg update -y

echo 'install wget, git and package ....'
pkg install git -y
pkg install wget -y 
pkg install vim -y 
pkg install cmake git libuv* openssl-dev unstable-repo -y
pkg install libmicrohttpd-dev -y


echo 'get repo from github ...'
git clone https://github.com/xmrig/xmrig
cd xmrig && mkdir build && cd build


echo 'cmake build ..'
cmake .. -DWITH_HWLOC=OFF
make

echo 'copy xmrig ....'

cp xmrig ..

cd ..

sleep 2
echo "--------------------------------"
pwd
echo "--------------------------------"
sleep 2
echo "DOWNLOADING config.json ..............."
sleep 2
wget https://raw.githubusercontent.com/xmrig/xmrig/master/src/config.json
read -p 'SERVER MINING: ' serv
read -p 'COIN: ' coin
read -p 'YOUR WALLET ADDRESS: ' wallet
read -p 'YOUR WORKER NAME:' worker

echo "--------------------------------------------"
sleep 2
echo "EDITING config.json ....!"
sleep 2
echo "-------------------------------------------->"
sed -i 's/url/'$serv'/' config.json
sed -i "s/user/$coin:$wallet.$worker/" config.json

sleep 2
sed -n '63,70p' config.json

cd

echo "./xmrig/xmrig" >> go

chmod +x go

sh go

